var bidEvent = contract.highestBidIncrease()

bidEvent.watch(function(error, result) {
    if(!error) {
        idForhighestBId.value = result.args.bidder;
        idForhighestbid.value = result.args.amount;
    } else {
        console.log(error);
    }
});

5000000000000000000

var abi = /* abi as generated by the compiler */;
var ClientReceipt = web3.eth.contract(abi);
var clientReceipt = ClientReceipt.at("0x1234...ab67" /* address */);

var depositEvent = clientReceipt.Deposit();

// watch for changes
depositEvent.watch(function(error, result){
    // result contains non-indexed arguments and topics
    // given to the `Deposit` call.
    if (!error)
        console.log(result);
});


// Or pass a callback to start watching immediately
var depositEvent = clientReceipt.Deposit(function(error, result) {
    if (!error)
        console.log(result);
});


{
   "returnValues": {
       "_from": "0x1111…FFFFCCCC",
       "_id": "0x50…sd5adb20",
       "_value": "0x420042"
   },
   "raw": {
       "data": "0x7f…91385",
       "topics": ["0xfd4…b4ead7", "0x7f…1a91385"]
   }
}
const auctions = [{
    name: "Giant BBQ",
    image: "https://i.imgur.com/yPreV19.png",
    itemName: `Grilled chicken, beef, fish, sausages, bacon, 
      vegetables served with chips.`,
    location: "Kimironko Market",
    owner: "0x32Be343B94f860124dC4fEe278FDCBD38C102D88",
    endTime: 23492875,
    noOfBids: 27,
    index: 0,
    startPrice: 50,
    highestBid: 70,
    hasAuctionStarted: true,
    remainingTimeTillStart: 0,
    biddingFee: 5,
    hasPaidBidFee: false,
    hasAuctionEnded: false,
    highestBidder: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
  },
  {
    name: "BBQ Chicken",
    image: "https://i.imgur.com/NMEzoYb.png",
    itemName: `French fries and grilled chicken served with gacumbari 
      and avocados with cheese.`,
    location: "Afrika Fresh KG 541 St",
    owner: "0x3275B7F400cCdeBeDaf0D8A9a7C8C1aBE2d747Ea",
    endTime: 40000000,
    noOfBids: 12,
    index: 1,
    startPrice: 60,
    highestBid: 133,
    hasAuctionStarted: true,
    remainingTimeTillStart: 0,
    biddingFee: 6,
    hasPaidBidFee: true,
    hasAuctionEnded: false,
    highestBidder: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
  },
  {
    name: "Beef burrito",
    image: "https://i.imgur.com/RNlv3S6.png",
    itemName: `Homemade tortilla with your choice of filling, cheese, 
      guacamole salsa with Mexican refried beans and rice.`,
    location: "Asili - KN 4 St",
    owner: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
    endTime: 36743893,
    noOfBids: 35,
    index: 2,
    startPrice: 70,
    highestBid: 70,
    hasAuctionStarted: false,
    remainingTimeTillStart: 4000,
    biddingFee: 7,
    hasPaidBidFee: true,
    hasAuctionEnded: true,
    highestBidder: "0x32Be343B94f860124dC4fEe278FDCBD38C102D88",
  },
  {
    name: "Barbecue Pizza",
    image: "https://i.imgur.com/fpiDeFd.png",
    itemName: `Barbecue Chicken Pizza: Chicken, gouda, pineapple, onions 
      and house-made BBQ sauce.`,
    location: "Kigali Hut KG 7 Ave",
    owner: "0x2EF48F32eB0AEB90778A2170a0558A941b72BFFb",
    endTime: 23492735,
    noOfBids: 2,
    index: 3,
    startPrice: 80,
    highestBid: 80,
    hasAuctionStarted: false,
    remainingTimeTillStart: 50000,
    biddingFee: 8,
    hasPaidBidFee: false,
    hasAuctionEnded: false,
    highestBidder: "0x3275B7F400cCdeBeDaf0D8A9a7C8C1aBE2d747Ea"
  },
]